### ISSUE TITLE
An error occurred when using vue-cli3.

### ISSUE THREAD

**Issue by bongjinpark1** [nhnent/toast-ui.vue-chart#1]
vue-cli3 가 구성해준 환경에서 그대로 쓰고있는데요,

따로 어떤 설정같은게 필요할까요?

소스코드 그대로 복사했는데 에러가 나네요..

[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

helloworld.vue
```vue
<template>
  <div>
    <bar-chart :data="chartData"></bar-chart>
  </div>
</template>

<script>
import 'tui-chart/dist/tui-chart.css'
import { barChart } from '@toast-ui/vue-chart'

export default {
  components: {
    'bar-chart': barChart
  },
  data () {
    return {
      chartData: { // for 'data' prop of 'bar-chart'
        categories: ['July', 'Aug', 'Sep', 'Oct', 'Nov'],
        series: [
          {
            name: 'Budget',
            data: [3000, 5000, 7000, 6000, 4000]
          },
          {
            name: 'Income',
            data: [1000, 7000, 2000, 5000, 3000]
          }
        ]
      }
    }
  }
}
</script>

<style scoped>

</style>
```
package.json
```json
"dependencies": {
    "@toast-ui/vue-chart": "^1.0.1",
    ...
}
```

**Comment by bongjinpark1** [comment]
webpack 설정에서 Enable runtime compiler 옵션을 true로 주니까 되네요.. 근데 아직 사이즈가 reactive는 아닌거죠? 디스플레이 사이즈가 바뀌면 resize 메서드로 크기를 바꿔줘야되는거죠?

**Comment by jungeun-cho** [comment]
When you summarize your questions,
Q1) The following error occurred.
```sh
[Vue warn]: You are using the runtime-only builder. Either pre-compile the templates into render functions, or use the compiler-included build.
```
A1) 
```js
// vue.config.js
module.exports = {
    runtimeCompiler: true
};
```

Q2) Will the chart size change automatically when the browser size changes?

A2) As a result, the responsive chart is not yet supported, so you have to manually resize the chart when you resize the browser. However, we plan to support it in our [TOAST UI Chart](https://github.com/nhnent/tui.chart) project.

Thank you for your interest in our project. :)
